name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        env:
          NEXT_PUBLIC_EMAIL_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_EMAIL_SERVICE_ID }}
          NEXT_PUBLIC_EMAIL_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_EMAIL_PUBLIC_KEY }}
          NEXT_PUBLIC_EMAIL_TEMPLATE: ${{ secrets.NEXT_PUBLIC_EMAIL_TEMPLATE }}
        run: |
          echo "NEXT_PUBLIC_EMAIL_SERVICE_ID=${{ secrets.NEXT_PUBLIC_EMAIL_SERVICE_ID }}" >> .env
          echo "NEXT_PUBLIC_EMAIL_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_EMAIL_PUBLIC_KEY }}" >> .env
          echo "NEXT_PUBLIC_EMAIL_TEMPLATE=${{ secrets.NEXT_PUBLIC_EMAIL_TEMPLATE }}" >> .env
          npm run build && npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./out